# -*- coding: utf-8 -*-
"""paddy_water

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IzhzmHLSOoNe019rw6sG78AQm8sU0P1k
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/water_analysis.csv')

df

df.nutrition_values.value_counts()

df.dtypes

df.isnull().sum()

#independent variable
x=df.drop('nutrition_values',axis=1)

#dependent variable
y=df['nutrition_values']

y

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

log=LogisticRegression()#default is 100
log.fit(x_train,y_train)
pred=log.predict(x_test)

accuracy=accuracy_score(y_test,pred)
accuracy

from sklearn.svm import SVC

model=SVC(kernel='linear',random_state=0)
#model=svm.SVC()
model.fit(x_train,y_train)
print(model)
pred=model.predict(x_test)
acc=accuracy_score(y_test,pred)
print(pred)
print(y_test)
print(acc)

input_data=(10.848065,1472.570680,311.861414,149.154952,4952.055657)
input_data_nparray=np.asarray(input_data)
reshape_data =input_data_nparray.reshape(1,-1)
prediction=log.predict(reshape_data)
if prediction==1:
  print('the crop has normal')
else:
  print('the crop has high')